In [2]:
import pandas as pd
import numpy as np
import nltk
import hazm

In [3]:
from google.colab import files
uploaded = files.upload()


Saving per.csv to per.csv


In [4]:
data=pd.read_csv('per.csv')

In [5]:
data.head()

NewsID                                              Title  \
0  843656  \nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...   
1  837144  \nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...   
2  436862  \nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...   
3  227781  \nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...   
4  174187  \nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...   

                                                Body         Date       Time  \
0  \nوزير علوم در جمع استادان نمونه كشور گفت: از ...  \n138/5//09  \n0:9::18   
1  \nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...  \n138/5//09  \n1:4::11   
2  \nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...  \n138/3//07  \n1:0::03   
3                                                 \n  \n138/2//02  \n1:3::42   
4  \nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...  \n138/1//08  \n1:1::49   

             Category  Category2  
0           \nآموزشي-   \nآموزشي  
1           \nآموزشي-   \nآموزشي  
2           \nآموزشي-   \nآموزشي  
3  \nاجتماعي-خانواده-  \nاجتماعي  
4           \nآموزشي-   \nآموزشي

In [10]:
with open ('stopwords.txt' , encoding='utf8') as stopwords_file:
  stopwords=stopwords_file.readlines()
stopwords=[line.replace('\n','') for line in stopwords]

In [11]:
stopwords

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '...',
 '....',
 '/',
 ':',
 '<',
 '=',
 '>',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'ء',
 'آاو و و و',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسانی',
 'آسيب پذيرند',
 'آسیب',
 'آسیب پذیرند',
 'آشكارا',
 'آشنايند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن ها',
 'آن گاه',
 'آنان',
 'آناني',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنكه',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان كه',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهاي',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آيا',
 'آيد',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'ابدا',
 'ابلهانه',
 'ات',
 'اتفاقا',
 'اثر',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احياناً',
 'احیانا',
 'احیاناً',
 'اخ',
 'اختصارا',

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [14]:
nltk_stopwords=nltk.corpus.stopwords.words('english')

In [15]:
stopwords.extend(nltk_stopwords)

In [18]:
len(stopwords)

2976

In [19]:
stemer=hazm.Stemmer()

In [23]:
from hazm import word_tokenize

In [24]:
dataset=pd.DataFrame(columns=('title_body','category'))

In [66]:
for index,row in data.iterrows():
  title_body=row['Title']+""+row['Body']
  title_body_tokenized=word_tokenize(title_body)
  title_body_tokenized_filtered=[w for w in title_body_tokenized if not w in stopwords]
  title_body_tokenized_filtered_stemmed=[stemer.stem(w) for w in title_body_tokenized_filtered]
  dataset.loc[index]={'title_body':" ".join(title_body_tokenized_filtered_stemmed),
                      'category':row['Category2'].replace('\n','')}

In [67]:
dataset.head()

title_body category
0  وزير علو درجمع استاد نمونه سن بازنشستگي استاد ...   آموزشي
1  گردهمايي دانش‌آموختگ موسسه آموز عالي سوره برگز...   آموزشي
2  نتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور ن...   آموزشي
3  هماي يكروزه آسيب مفهو روابط عمومي بابلسر برگزا...  اجتماعي
4  وضعي اقتصادي تحصيل والدين مهمترين عوامل موفقي ...   آموزشي

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [69]:
vectorizer=TfidfVectorizer()

In [70]:
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [71]:
x=vectorizer.transform(dataset['title_body'])

In [72]:
x

<10999x60555 sparse matrix of type '<class 'numpy.float64'>'
	with 1556085 stored elements in Compressed Sparse Row format>

In [73]:
from sklearn.preprocessing import LabelEncoder

In [74]:
le=LabelEncoder()
y=le.fit_transform(dataset['category'])

In [75]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [76]:
len(y)

10999

In [77]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [78]:
from sklearn.svm import SVC
svmc=SVC()

In [79]:
svmc.fit(x_train,y_train)

SVC()

In [80]:
svmc.score(x_test,y_test)

0.848

In [84]:
from sklearn.metrics import classification_report,confusion_matrix

In [82]:
y_pred=svmc.predict(x_test)

In [83]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.86       249
           1       0.68      0.63      0.65       256
           2       0.79      0.84      0.82       242
           3       0.86      0.92      0.89       251
           4       0.89      0.89      0.89       247
           5       0.82      0.72      0.76       234
           6       0.77      0.75      0.76       240
           7       0.85      0.90      0.87       271
           8       0.87      0.87      0.87       248
           9       0.97      0.92      0.94       247
          10       0.98      0.98      0.98       265

    accuracy                           0.85      2750
   macro avg       0.85      0.85      0.85      2750
weighted avg       0.85      0.85      0.85      2750



In [86]:
print(confusion_matrix(y_test,y_pred))


[[223   4   0   4   0   3  13   0   1   0   1]
 [ 14 161  21   5  10   6   9  17   7   2   4]
 [  2  19 204   1   1   1   8   3   2   1   0]
 [  2   7   2 231   0   1   7   1   0   0   0]
 [  2   2   0   0 221   8   1   7   4   2   0]
 [  3  12   8   2  12 168   5   5  17   2   0]
 [ 15  11   8  22   0   2 179   3   0   0   0]
 [  4   8   5   0   3   3   5 243   0   0   0]
 [  2   3   6   1   1  11   5   3 216   0   0]
 [  0   8   3   0   1   3   1   4   0 227   0]
 [  0   3   0   2   0   0   0   1   0   0 259]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')