In [3]:
import numpy as np
import pandas as pd

In [4]:
data=pd.read_csv('textClassification.csv')

In [5]:
data.head()

Household  \
0  Household   
1  Household   
2  Household   
3  Household   
4  Household   

  Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.  
0  SAF 'Floral' Framed Painting (Wood, 30 inch x ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
1  SAF 'UV Textured Modern Art Print Framed' Pain...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

In [6]:
data.columns = ['Y', 'data']

In [7]:
data.head()

Y                                               data
0  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
1  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
2  Household  SAF Flower Print Framed Painting (Synthetic, 1...
3  Household  Incredible Gifts India Wooden Happy Birthday U...
4  Household  Pitaara Box Romantic Venice Canvas Painting 6m...

In [8]:
data.isnull().sum()

Y       0
data    1
dtype: int64

In [9]:
data[data['data'].isnull()]

Y data
39329  Clothing & Accessories  NaN

In [12]:
data = data.dropna(subset=['data'])

In [13]:
data.isnull().sum()

Y       0
data    0
dtype: int64

In [14]:
import nltk

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [16]:
stopwords=nltk.corpus.stopwords.words('english')

In [17]:
len(stopwords)

179

In [23]:
stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [24]:
from nltk.stem import PorterStemmer
stemer=PorterStemmer()

In [31]:
dataset=pd.DataFrame(columns=('title_body', 'category'))
for index,row in data.iterrows():
  words=row['data'].split()
  words_filtered=[w for w in words if not w in stopwords]
  words_filtered_stemmed=(stemer.stem(w) for w in words_filtered)
  dataset.loc[index]={'title_body':' '.join(words_filtered_stemmed),
                      'category':row['Y']}


In [32]:
dataset

title_body     category
0      saf 'floral' frame paint (wood, 30 inch x 10 i...    Household
1      saf 'uv textur modern art print framed' paint ...    Household
2      saf flower print frame paint (synthetic, 13.5 ...    Household
3      incred gift india wooden happi birthday uniqu ...    Household
4      pitaara box romant venic canva paint 6mm thick...    Household
...                                                  ...          ...
50419  strontium microsd class 10 8gb memori card (bl...  Electronics
50420  crossbeat wave waterproof bluetooth wireless e...  Electronics
50421  karbonn titanium wind w4 (white) karbonn titan...  Electronics
50422  samsung guru fm plu (sm-b110e/d, black) colour...  Electronics
50423                    micromax canva win w121 (white)  Electronics

[50423 rows x 2 columns]

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [35]:
x=vectorizer.transform(dataset['title_body'])

In [36]:
x

<50423x75903 sparse matrix of type '<class 'numpy.float64'>'
	with 2969125 stored elements in Compressed Sparse Row format>

In [42]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(dataset['category'])

In [43]:
le.classes_

array(['Books', 'Clothing & Accessories', 'Electronics', 'Household'],
      dtype=object)

In [44]:
len(y)

50423

In [46]:
np.shape(y)

(50423,)

In [47]:
np.shape(x)

(50423, 75903)

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [50]:
from sklearn.svm import SVC
svc=SVC()

In [51]:
svc.fit(x_train,y_train)

SVC()

In [53]:
svc.score(x_test,y_test)

0.9773123909249564

In [54]:
from sklearn.metrics import classification_report , confusion_matrix

In [55]:
y_pred=svc.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      2921
           1       0.99      0.98      0.98      2166
           2       0.97      0.96      0.97      2657
           3       0.97      0.99      0.98      4862

    accuracy                           0.98     12606
   macro avg       0.98      0.98      0.98     12606
weighted avg       0.98      0.98      0.98     12606

[[2849    5   21   46]
 [  11 2118    9   28]
 [  27    2 2559   69]
 [  20   10   38 4794]]
